modLoader="javafml"
loaderVersion="[43,)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/Maledicta/issues"

[[mods]]
modId="maledicta"
version="${file.jarVersion}"
displayName="Maledicta"
displayTest="MATCH_VERSION"
displayURL="www.curseforge.com/members/melanx/"
updateJSONURL="https://assets.melanx.de/updates/maledicta.json"
authors="MelanX"
description="""
SpookyJam 2022 mod by MelanX, dealing with Curses
"""

[[dependencies.maledicta]]
    modId="forge"
    mandatory=true
    versionRange="[43.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.maledicta]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, 1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.maledicta]]
    modId = "libx"
    mandatory = true
    versionRange = "[1.19.2-4.2.5,)"
    ordering = "AFTER"
    side = "BOTH"
